apiVersion: ngrok.com/v1alpha1
kind: Ngrok
metadata:
  name: ngrok-authtoken-secret
  namespace: default
spec:
  # ngrok authtoken
  authtoken: authtoken-secret

  # ngrok authotken
  authtoken_type: secret

  # service section represent
  # the service name in the same namespace
  service: nginx-service

  # port section represent
  # the service port in the same namespace
  port: 80
